version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for development
      - .:/app
      # Mount node_modules to avoid overwriting with host directory
      - /app/node_modules
      # Mount persistent volumes for database and uploads
      - data:/data
    command: npm run start
    restart: unless-stopped

volumes:
  data:
    driver: local